### ISSUE TITLE
Rendering underscores on publication HTMLs

### ISSUE THREAD

**Issue by ianychoi** [MicrosoftDocs/Contribute.ko-KR#4]
Problem:
- Underscores should not be seen but they appear.

Example:
- https://docs.microsoft.com/ko-kr/contribute/
 - _오픈의 오픈 소스 리포지토리 계획_은 가장 필요한 문서에 대한 피드백을 받습니다.
 - _오픈의 오픈 소스 리포지토리 검토_는 첫 번째 릴리스에서 가장 유용한 콘텐츠를 게시할 수 있습니다.
 - _오픈의 오픈 소스 리포지토리 업데이트_는 콘텐츠를 계속 개선하기 쉽습니다.

![image](https://user-images.githubusercontent.com/6965982/58616901-c54aec00-82f9-11e9-9927-57e9c55bd375.png)

@srvbpigh Thank you for sharing the feedback through https://github.com/MicrosoftDocs/Contribute.ko-KR/pull/2 but a purpose space is definitely needed. When you see https://docs.microsoft.com/ko-kr/contribute/ - actual publication, the HTML shows underscores like "_오픈의 오픈 소스 리포지토리 계획_은 가장 필요한 문서에 대한 피드백을 받습니다.". a purpose space should solve the issue.

Or any kind of alternative approach to solve this problem?

**Comment by CeciAc** [comment]
Hello, @ianychoi 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ianychoi
Thank you for your feedback.
 
We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ko-kr/contribute/

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
